apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: movie-finder-deployment
spec:
  selector:
    matchLabels: 
      app: movie-finder
  replicas: 2
  template: 
    metadata:
      labels:
        app: movie-finder
    spec:
      containers:
      - name: movie-finder
        image: redrebel/movie-finder:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: movie-finder
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: movie-finder